# Generated by Django 4.2 on 2023-05-17 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=100)),
                ('upload', models.FileField(max_length=80, upload_to='SofiaApp/static/SofiaApp/contenido')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('ROL', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor')], default='ESTUDIANTE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('comentario', models.CharField(max_length=50)),
                ('calificacion', models.IntegerField()),
                ('Contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SofiaApp.contenidos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso_Educativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='recurso_educativo/')),
                ('Contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SofiaApp.contenidos')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=50)),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SofiaApp.tareas')),
            ],
        ),
    ]
