# Generated by Django 4.2 on 2023-05-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SofiaApp', '0002_notas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='calificacion',
        ),
    ]
