# Generated by Django 4.2 on 2023-05-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SofiaApp', '0004_alter_contenidos_options_alter_tareas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('CR_contenido', 'Posibilita Crear Contenidos'), ('MO_contenido', 'Posibilita Modificar Contenidos'), ('DE_contenido', 'Posibilita Eliminar Contenidos')]},
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'permissions': [('CR_Notas', 'Posibilita Crear Notas'), ('MO_Notas', 'Posibilita Modificar Notas'), ('DE_Notas', 'Posibilita Eliminar Notas')]},
        ),
        migrations.AlterModelOptions(
            name='recurso_educativos',
            options={'permissions': [('CR_Recurso', 'Posibilita Crear Recursos'), ('MO_Recurso', 'Posibilita Modificar Recursos'), ('DE_Recurso', 'Posibilita Eliminar Recursos')]},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={'permissions': [('CR_Tareas', 'Posibilita Crear Tareas'), ('MO_Tareas', 'Posibilita Modificar Tareas'), ('DE_Tareas', 'Posibilita Eliminar Tareas')]},
        ),
    ]
