# Generated by Django 4.2 on 2023-05-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SofiaApp', '0005_alter_contenidos_options_alter_notas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('contenidoCR', 'CreaContenidos'), ('contenidoMO', 'ModificaContenidos'), ('contenidoDE', 'EliminaContenidos')]},
        ),
    ]
