# Generated by Django 4.2 on 2023-05-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SofiaApp', '0006_alter_contenidos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
