from django.urls import path
from SofiaApp import views

urlpatterns = [

    path('', views.home, name="Home"),
    path('Iniciar_Sesion', views.Iniciar_Sesion, name="Iniciar Sesion"),
    path('Registrarse', views.Registrarse, name="Registrarse"),
    path('Contenido', views.Contenido, name="Contenido"),
    path('Administrar_Nota', views.Administrar_Nota, name="Administrar Nota"),
    path('Administrar_Contenido', views.Administrar_Contenido, name="Administrar Contenido"),
    path('Administrar_Recurso_Educativo', views.Administrar_Recurso_Educativo, name="Administrar Recurso Educativo"),
    path('Administrar_Tarea', views.Administrar_Tarea, name="Administrar Tarea"),
    path('Nota', views.Nota, name="Nota"),
    path('Contenido', views.Contenido, name="Contenido"),
    path('Recurso_Educativo', views.Recurso_Educativo, name="Recurso Educativo"),
    path('Tarea', views.Tarea, name="Tarea"),
    path('create_contenido',views.create_contenido.as_view(),name='create_contenido' ),
    path('list_contenido',views.listar_contenidos.as_view(),name='list_contenido' ),
    path('update_contenido/<int:pk>/', views.update_contenido.as_view(),name='update_contenido'),
    path('delete_contenido/<int:pk>/',views.delete_contenido.as_view(),name='delete_contenido'),
    path('create_recurso',views.crear_recurso.as_view(),name='create_recurso' ),
    path('list_recurso',views.listar_recurso.as_view(),name='list_recurso' ),
    path('update_recurso/<int:pk>/', views.update_recurso.as_view(),name='update_recurso'),
    path('delete_recurso/<int:pk>/',views.delete_Recurso.as_view(),name='delete_recurso'),
    path('create_tarea',views.crear_tarea.as_view(),name='create_tarea' ),
    path('list_tarea',views.listar_tarea.as_view(),name='list_tarea' ),
    path('update_tarea/<int:pk>/', views.update_tarea.as_view(),name='update_tarea'),
    path('delete_tarea/<int:pk>/',views.delete_tarea.as_view(),name='delete_tarea'),
    path('create_nota',views.crear_nota.as_view(),name='create_nota' ),
    path('list_nota',views.listar_nota.as_view(),name='list_nota' ),
    path('update_nota/<int:pk>/', views.update_nota.as_view(),name='update_nota'),
    path('delete_nota/<int:pk>/',views.delete_nota.as_view(),name='delete_nota'),
    #path('registroUsuario',views.registroUsuario.as_view(),name='registroUsuario')
    path('registrar',views.registroUsuario.as_view(),name='registrar'),
    path('conjuntos/', views.show_pdf1, name='show_pdf1'),
    path('LM/', views.show_pdf2, name='show_pdf2'),
    path('teoriadegrafos/', views.show_pdf3, name='show_pdf3'),
    path('combinatoria/', views.show_pdf4, name='show_pdf4'),
    path('teoriadenumeros/', views.show_pdf5, name='show_pdf5'),
    path('teoriadecodificacion/', views.show_pdf6, name='show_pdf6'),
    path('teoriadeinformacion/', views.show_pdf7, name='show_pdf7'),
    path('teoriadejuegos/', views.show_pdf8, name='show_pdf8'),
    path('criptografia/', views.show_pdf9, name='show_pdf9'),
    path('list_tarea1/',views.listar_tarea1.as_view(),name='list_tarea1' ),
    path('list_nota1/',views.listar_nota1.as_view(),name='list_nota1' ),
    path('create-professor/', views.CreateProfessorView.as_view(), name='create_professor'),
]